### ISSUE TITLE
cannot find package "github.com/labstack/echo/engine/standard"

### ISSUE THREAD

**Issue by zer0xtgs** [mark3labs/go-echo-vue#1]
**Description**
Hi, I'm trying to build your go-echo-vue project.
but go get, doesn't download some components from echo framework.
Is there any way how to solve it?

**Bash output**
todo.go:9:2: cannot find package "github.com/labstack/echo/engine/standard" in any of:
	/usr/local/go/src/github.com/labstack/echo/engine/standard (from $GOROOT)
	/Users/Alexander/go/src/github.com/labstack/echo/engine/standard (from $GOPATH)
todo.go:6:2: cannot find package "go-echo-vue/handlers" in any of:
	/usr/local/go/src/go-echo-vue/handlers (from $GOROOT)
	/Users/Alexander/go/src/go-echo-vue/handlers (from $GOPATH)

**Comment by ezynda3** [comment]
Currently Echo is on version 3 which seems to have some breaking changes. Go get will automatically fetch the latest version from github and there is no good way to version dependencies yet. You can download the correct version from here `https://github.com/labstack/echo/tree/v2`. Just download the zip file and extract it into your $GOPATH.
