### ISSUE TITLE
cannot find package "go-echo-vue/handlers

### ISSUE THREAD

**Issue by ghost** [mark3labs/go-echo-vue#2]
I just cloned the repo and ehn I try to build the app I get:

/Users/noby/go/src/github.com/norbertfuhs/go-echo-vue > go build todo.go
todo.go:6:2: cannot find package "go-echo-vue/handlers" in any of:
	/usr/local/go/src/go-echo-vue/handlers (from $GOROOT)
	/Users/noby/go/src/go-echo-vue/handlers (from $GOPATH)

But the import path looks right what can I do to fix this?

**Comment by ezynda3** [comment]
Hi. You should place the repo into `/Users/noby/go/src` and not `/Users/noby/go/src/github.com/norbertfuhs`.
